getwd()
[1] "/Users/jakeforman"
setwd("/Users/jakeforman/Desktop/datasciencecoursera")
[Workspace restored from /Users/jakeforman/Desktop/datasciencecoursera/.RData]

1. Code for reading in the dataset and/or processing the data

Once unzip and stored in the working directory, it is loaded into a dataframe
Error: unexpected symbol in "Once unzip"

> activity <- read.csv("activity.csv")
> The dataframe looks like as follows

> str(activity)
'data.frame':	17568 obs. of  3 variables:
 $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
 $ date    : Factor w/ 61 levels "2012-10-01","2012-10-02",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ interval: int  0 5 10 15 20 25 30 35 40 45 ...
## 'data.frame':    17568 obs. of  3 variables:
##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ date    : Factor w/ 61 levels "2012-10-01","2012-10-02",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...
We want to transform date column in a "Date"

> activity$date <- as.Date(activity$date, format = "%Y-%m-%d")
> str(activity)
'data.frame':	17568 obs. of  3 variables:
 $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
 $ date    : Date, format: "2012-10-01" "2012-10-01" "2012-10-01" "2012-10-01" ...
 $ interval: int  0 5 10 15 20 25 30 35 40 45 ...
## 'data.frame':    17568 obs. of  3 variables:
##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ date    : Date, format: "2012-10-01" "2012-10-01" ...
##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...
2. Histogram of the total number of steps taken each day
First, we aggregate the steps by day

> actbyDate <-  aggregate(steps ~ date, activity, sum)
> The Histogram is plotted
> with(actbyDate,hist(steps,col="light blue",breaks=10,main="# of Steps per Day",xlab="# of steps"))
